# Generated by Django 4.0.5 on 2022-07-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_familia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('posicion', models.IntegerField()),
                ('email', models.EmailField())
            ],
        ),
    ]
