# Generated by Django 4.0.5 on 2022-07-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_equipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipo',
        ),
    ]
